### PR TITLE
Display group info

### PR DESCRIPTION
**Pull request by infa-mseelam**

### CODE REVIEW

**Comment by infa-ddeore** [comment]
closes #14

**Comment by infa-ddeore** [comment]
tested this change on EKS, GKE and AKS clusters, it shows groups info as well as ARN details if present

sample outputs as below

EKS:
```
User:	userName
Groups:
	system:masters
	system:authenticated
ARN:
	arn:aws:sts::123456789:assumed-role/<aws-Role-Name>/<aws-user>
```

GKE:
```
User:	user@email.com
Groups:
	user-group1@email.com
	user-group2@email.com
	user-group3@email.com
	system:authenticated
```

AKS:

```
User:	user@email.com
Groups:
	sdbd146d-1234-lkfg-df56-1358tdyjf234
	ftwwf097-9845-92kj-294j-aerhg4557lmd
	sfty0942-rlew-2345-6jdl-678647123ger
        system:authenticated
```

**Comment by infa-ddeore** [comment]
@rajatjindal could you approve this PR to fix #14 issue?

**Comment by infa-mseelam** [comment]
Sure @rajatjindal I will add a new flag and even variable and let you know.

**Comment by infa-mseelam** [comment]
@rajatjindal  added the arg called "--all" to display user, group, and ARN info.
The app behaves the same as previous If the user doesn't specify any flag. 
Please review and approve.

**Comment by infa-ddeore** [comment]
@rajatjindal README is also updated with `--all` option instructions, I have also tested and verified that it works as expected, i.e. shows only user name as before. 

With `--all` option it shows the similar output that I have mentioned in my sample output comment above

**Comment by rajatjindal** [comment]
thanks again for the PR

**Pull request merged**
